name: Trigger Tekton Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-tekton:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Tekton PipelineRun
      run: |
        curl -X POST http://<LoadBalancer_IP>:8080 \
        -H 'Content-Type: application/json' \
        -d '{
              "body": {
                "repository": {
                  "clone_url": "https://github.com/aitdevops/frontend"
                },
                "head_commit": {
                  "id": "${{ github.sha }}"
                }
              }
            }'
