apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: COMMIT_SHA
      type: string
    - name: PROJECT_ID
      type: string
  workspaces:
    - name: shared-workspace
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        git clone $(params.git-url) $(workspaces.shared-workspace.path)/source
        cd $(workspaces.shared-workspace.path)/source
        git checkout $(params.git-revision)
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/key.json
      volumeMounts:
        - name: gcp-key
          mountPath: /secrets
          readOnly: true
      script: |
        cd $(workspaces.shared-workspace.path)/source/frontend
        /kaniko/executor --dockerfile=Dockerfile --context=. --destination=us-central1-docker.pkg.dev/$(params.PROJECT_ID)/aitdevops-gke/frontend:$(params.COMMIT_SHA)
  volumes:
    - name: gcp-key
      secret:
        secretName: gcp-secret
