apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: git-repo-tekton
spec:
  type: git
  params:
    - name: url
      value: https://github.com/aitdevops/tekton
    - name: revision
      value: master
