apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
  namespace: tekton-tasks
spec:
  params:
    - name: git-url-frontend
      type: string
      description: The git repository URL for the frontend code
      default: https://github.com/aitdevops/aitdevops
    - name: git-revision-frontend
      type: string
      description: The git revision for the frontend code
      default: frontend
    - name: git-url-tekton
      type: string
      description: The git repository URL for the Tekton files
      default: https://github.com/aitdevops/tekton
    - name: git-revision-tekton
      type: string
      description: The git revision for the Tekton files
      default: master
    - name: COMMIT_SHA
      type: string
    - name: PROJECT_ID
      type: string
    - name: CLUSTER_NAME
      type: string
    - name: REGION
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-and-push
      taskRef:
        kind: Task
        name: build-and-push-task
      params:
        - name: git-url
          value: $(params.git-url-frontend)
        - name: git-revision
          value: $(params.git-revision-frontend)
        - name: COMMIT_SHA
          value: $(params.COMMIT_SHA)
        - name: PROJECT_ID
          value: $(params.PROJECT_ID)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: deploy
      taskRef:
        kind: Task
        name: deploy-task
      runAfter:
        - build-and-push
      params:
        - name: git-url
          value: $(params.git-url-tekton)
        - name: git-revision
          value: $(params.git-revision-tekton)
        - name: COMMIT_SHA
          value: $(params.COMMIT_SHA)
        - name: PROJECT_ID
          value: $(params.PROJECT_ID)
        - name: CLUSTER_NAME
          value: $(params.CLUSTER_NAME)
        - name: REGION
          value: $(params.REGION)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
