apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-pipeline-run
  namespace: tekton-tasks
spec:
  params:
    - name: COMMIT_SHA
      value: YOUR_COMMIT_SHA
    - name: PROJECT_ID
      value: aitdevops8
  pipelineRef:
    name: frontend-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
  serviceAccountName: default
  timeout: 1h0m0s
