name: Trigger Tekton Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-tekton:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    - name: Trigger Tekton PipelineRun
      run: |
        kubectl apply -f pipeline-run.yaml
