apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: frontend-listener
  namespace: tekton-tasks
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: frontend-trigger
      bindings:
        - ref: frontend-trigger-binding
      template:
        ref: frontend-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - env:
                  - name: TLS_CERT
                    valueFrom:
                      secretKeyRef:
                        name: tekton-listener-tls-secret
                        key: tls.crt
                  - name: TLS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: tekton-listener-tls-secret
                        key: tls.key
