apiVersion: v1
kind: Service
metadata:
  name: el-frontend-listener
  namespace: tekton-tasks
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    eventlistener: frontend-listener
  type: LoadBalancer
