apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: frontend-trigger-template
  namespace: tekton-tasks
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository URL
      default: https://github.com/aitdevops/frontend
    - name: COMMIT_SHA
    - name: PROJECT_ID
      default: aitdevops8
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: frontend-pipeline-run-
      spec:
        pipelineRef:
          name: frontend-pipeline
        params:
          - name: git-url
            value: $(params.gitrepositoryurl)
          - name: git-revision
            value: $(params.gitrevision)
          - name: COMMIT_SHA
            value: $(params.COMMIT_SHA)
          - name: PROJECT_ID
            value: $(params.PROJECT_ID)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace-pvc
