apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
  namespace: tekton-tasks
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: COMMIT_SHA
      type: string
    - name: PROJECT_ID
      type: string
  workspaces:
    - name: shared-workspace
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning up the workspace"
        if [ -d /workspace/shared-workspace/source ]; then
          echo "Removing existing directory"
          rm -rf /workspace/shared-workspace/source || { echo "Failed to remove directory"; exit 1; }
        fi
        mkdir -p /workspace/shared-workspace/source
        git clone $(params.git-url) /workspace/shared-workspace/source
        cd /workspace/shared-workspace/source
        git checkout $(params.git-revision)
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=Dockerfile
        - --context=/workspace/shared-workspace/source/frontend
        - --destination=us-central1-docker.pkg.dev/$(params.PROJECT_ID)/aitdevops-gke/frontend/:$(params.COMMIT_SHA)
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/key.json
      volumeMounts:
        - name: gcp-key
          mountPath: /secrets
          readOnly: true
  volumes:
    - name: gcp-key
      secret:
        secretName: gcp-secret
